# Step 1: Specify base image
FROM node:22.4.1

# Step 2: Set the working directory inside the container
WORKDIR /usr/src/app

# Step 3: Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Step 4: Copy all other source code to the container
COPY . .

# set environment variables
ENV JWT_SECRET=aj123
ENV JWT_REFRESH_SECRET=aj123

# Step 5: Expose the port the app runs on
EXPOSE 5001

# Step 6: Command to start the app
CMD ["npm", "start"]
